fix CORS issue in production deployment
Battery-Intelligence-Lab/galvanalyser pull request #69
Opened 2023-04-12 11:38 UTC by mjaquiery

2023-04-12 11:55 UTC, martinjrobins requested changes
I would suggest that we allow the user to specify the entire hostname

2023-04-12 11:55 UTC, martinjrobins commented on .env
> +FRONTEND_PORT=80
should specify the entire hostname, not just the port?
`HOSTNAME=localhost:80`

2023-04-13 13:18 UTC, mjaquiery commented
@martinjrobins This version should be better. Any chance you can test it on the Azure setup and verify it works? I can run it successfully without CORS issues in dev/prod mode quite happily, and even specify a port for it to run on. As is, it'll run on port 80 in both dev and prod modes. 

As a side-effect, I've removed nginx's proxying of the django server and just allowed direct access because that container exposes its http interface over port 5000, so you've got http://localhost for the frontend and http://localhost:5000 for the backend.

2023-04-20 10:28 UTC, martinjrobins approved these changes
looks great, thanks @mjaquiery !

2023-04-20 10:47 UTC, merged